apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik

resources:
  - namespace.yaml
  - customResourceDefinitions.yaml
  - daemonset.yaml
  - rbac.yaml
  - service.yaml
  - serviceAccount.yaml
