kind: Service
apiVersion: v1
metadata:
  labels:
    app: traefik-ingress-lb
  name: traefik-ingress-lb
spec:
  selector:
    app: traefik-ingress-lb
  ports:
    - name: web
      protocol: TCP
      port: 80
    - name: metrics
      protocol: TCP
      port: 8080
    - name: multichain
      protocol: TCP
      port: 8571
      targetPort: 8571
  externalTrafficPolicy: Local
  type: LoadBalancer
