apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rbac.yaml
  - deamonset.yaml

images:
- name: node-exporter
  newName: quay.io/prometheus/node-exporter
  newTag: v0.18.1