apiVersion: v1
kind: Namespace
metadata:
  name: demo

---

apiVersion: v1
kind: Namespace
metadata:
  name: viewer

---

apiVersion: v1
kind: Namespace
metadata:
  name: logging

---

apiVersion: v1
kind: Namespace
metadata:
  name: monitoring

---

apiVersion: v1
kind: Namespace
metadata:
  name: traefik
