apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rbac.yaml
  - deployment.yaml
  - service.yaml

images:
- name: kube-state-metrics
  newName: quay.io/coreos/kube-state-metrics
  newTag: v1.8.0