apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  annotations:
    kubernetes.io/ingress.class: traefik
  name: grafana
spec:
  entryPoints: []
  routes: null

---

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: headers-empty-auth
spec:
  headers:
    customRequestHeaders:
      Authorization: ""

---

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: requestmodifier-grafana
spec:
  replacePathRegex:
    regex: ^/internal/grafana/(.*)
    replacement: /$1
