apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- rbac.yaml
- statefulset.yaml
- service.yaml
- ingress.yaml

configMapGenerator:
  - name: grafana-dashboardproviders
    files:
    - dashboardproviders.yaml
  - name: grafana-dashboards
    files:
    - dashboards/k8s-cluster-rsrc-use.json
    - dashboards/k8s-node-rsrc-use.json    
    - dashboards/k8s-resources-cluster.json    
    - dashboards/k8s-resources-namespace.json    
    - dashboards/k8s-resources-pod.json    
    - dashboards/k8s-resources-workload.json
    - dashboards/k8s-resources-workloads-namespace.json
    - dashboards/nodes.json
    - dashboards/pods.json
    - dashboards/persistentvolumesusage.json  
    - dashboards/statefulset.json
    - dashboards/traefik-metrics.json

images:
- name: grafana
  newName: grafana/grafana
  newTag: 7.1.1
