kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: zookeeper-deployment-1
spec:
  serviceName: zookeeper-1
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-1
  template:
    spec:
      nodeSelector:
        agentpool: nodepool1
      containers:
        - name: zoo1
          image: digitalwonderland/zookeeper
          ports:
            - containerPort: 2181
          env:
          - name: ZOOKEEPER_ID
            value: "1"
          - name: ZOOKEEPER_SERVER_1
            value: zoo1
