apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

commonLabels:
  environment: local

bases:
  - grafana
  - kube-state-metrics
  - node-exporter
  - prometheus

resources:
  - namespace.yaml
