apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: traefik

commonLabels:
  app: traefik

resources:
  - namespace.yaml
  - rbac.yaml
  - configmap.yaml
  - svc.yaml
  - deployment.yaml
