"groups":
- "name": "Traefik Backend availability"
  "rules":
  - "alert": "Traefik - backend down"
    "expr": traefik_backend_server_up == 0
    "for": "5m"
    "labels":
      "severity": "critical"
    "annotations":
      "message": "Traefik backend is down\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
      "dashboard": "https://localhost/internal/grafana/d/lPW0UeAiz/traefik-metrics?orgId=1&refresh=30s"
  - "alert": "Traefik - All backends down"
    "expr": count(traefik_backend_server_up) by (backend) == 0
    "for": "5m"
    "labels":
      "severity": "critical"
    "annotations":
      "message": "All Traefik backends are down\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"
      "dashboard": "https://localhost/internal/grafana/d/lPW0UeAiz/traefik-metrics?orgId=1&refresh=30s"      
  - "alert": "Traefik - backend errors"
    "expr": sum(rate(traefik_backend_requests_total{code=~"5.*"}[5m])) by (backend) / sum(rate(traefik_backend_requests_total[5m])) by (backend) *100 > 10
    "for": "5m"
    "labels":
      "severity": "critical"
    "annotations":
      "message": "Traefik backend error rate is above 10%\n  VALUE = {{ $value }}%\n  LABELS: {{ $labels }}"
      "dashboard": "https://localhost/internal/grafana/d/lPW0UeAiz/traefik-metrics?orgId=1&refresh=30s"
