apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
spec:
  template:
    spec:
      containers:
        - name: node-exporter
          resources:
            requests:
              cpu: 200m
              memory: 500M
            limits:
              cpu: 350m
              memory: 750M              